unitree-g1:
  image: __IMAGE__
  container_name: embodied-unitree-g1
  network_mode: host
  ipc: host
  pid: host
  environment:
    - ROS_DOMAIN_ID=42
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - FASTDDS_BUILTIN_TRANSPORTS=DEFAULT
    - PYTHONUNBUFFERED=1
  logging:
    driver: local
    options:
      max-size: "10m"
      max-file: "3"
  restart: unless-stopped
